### PR TITLE
 32-styling-responsiveness

### LINKED ISSUE #32: styling & responsiveness
- Use for style: https://www.figma.com/file/uJatBAblRBlB3oobYtwRFg/Hope-UI-Admin-%7C-Free-Open-Source-Bootstrap-5-Admin-Template-(Community)?type=design&node-id=456-335&mode=design&t=qD0K6xVLlGMAv23t-0
- Make responsive.

### PR DESCRIPTION
**Pull request by Miladepour**
## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #32

### CODE REVIEW

**Comment by Miladepour** [comment]
@haroon-ali-dev Please have look into it and check what should be done!

**Review by haroon-ali-dev — CHANGES_REQUESTED** [review]
Great job! Please make the following changes then should be all good:

- On login page, logo, text and button need to be in center of screen.
- In navigation, links need to stay highlighted when clicking anywhere.
- Buttons need to be bigger in member and event tables.
- The form in the modal used to add members to events needs to look right on mobile. Please see screenshot.
Screenshot 2023-07-25 220616

**Comment by Miladepour** [comment]
Ready for review!

**Review by haroon-ali-dev — APPROVED** [review]
All requested changes have been done right. All works great.
Thanks.

**Pull request merged**
