### PR TITLE
28 various tasks 1

### LINKED ISSUE #28: Various tasks 1
- Make QR sent in email bigger and part of the email body.
- Button next to each member to send info by email.
- Fix duplicate member IDs being created on member creation.
- Put ‘unique’ constraint on g_id and email columns in members table.
- if you delete a member from the members table, all attendance records associated with that member will be deleted from the attendance table. Similarly, if you delete an event from the events table, all attendance records associated with that event will be deleted from the attendance table.

### PR DESCRIPTION
**Pull request by Miladepour**
## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #28 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

### CODE REVIEW

**Comment by Miladepour** [comment]
Everything is ready except including the QR code to the body of email , Please have look into it if you can.

**Review by haroon-ali-dev — CHANGES_REQUESTED** [review]
There is no spinner on the confirmation button when sending email to member.

**Comment by Miladepour** [comment]
> There is no spinner on the confirmation button when sending email to member.

```
        <Modal.Footer>
          <Button variant="danger" onClick={() => sendEmail(members.find((member) => member.id === showMailModal[1]))} disabled={reqInProcess}>
            Yes
            {reqInProcess && (
              <Spinner className="ms-2" animation="border" role="status" size="sm">
                <span className="visually-hidden">Loading...</span>
              </Spinner>
            )}
          </Button>
        </Modal.Footer>
```
There is a spinner!

**Comment by Miladepour** [comment]
Thanks for your help I tested the code and it's perfect now.

**Comment by haroon-ali-dev** [comment]
> > There is no spinner on the confirmation button when sending email to member.
> 
> ```
>         <Modal.Footer>
>           <Button variant="danger" onClick={() => sendEmail(members.find((member) => member.id === showMailModal[1]))} disabled={reqInProcess}>
>             Yes
>             {reqInProcess && (
>               <Spinner className="ms-2" animation="border" role="status" size="sm">
>                 <span className="visually-hidden">Loading...</span>
>               </Spinner>
>             )}
>           </Button>
>         </Modal.Footer>
> ```
> 
> There is a spinner!

The spinner doesn't appear. You need to change the code so that it works when 'yes' button is pressed.

**Comment by Miladepour** [comment]
Spinner problem is FIXED.

**Review by haroon-ali-dev — APPROVED** [review]
All working fine now.

**Pull request merged**
